### ISSUE TITLE
Storybook QA ticket

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#1121]
## TODO

- [ ] Compare visually with Figma
- [ ] Test interactions in Storybook (events, clicks) 
- [ ] Missing visual elements (labels, placeholders (from `props`))
- [ ] Chromatic UI tests (background, accessibility)
- [ ] Proper dummy texts -> Improvements 
- [ ] Sane options for inputs -> Improvements
