### ISSUE TITLE
Checklist stories Fixes

### ISSUE THREAD

**Issue by roshni73** [IFRCGo/go-web-app#1143]
- [x]   Change the name of the options

- [ ]  Placement of validation message is incorrect

- [x] Change the content of the validation message"
