### ISSUE TITLE
Local Units: Design audit feedbacks

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#1178]
## TODO 

- [x] Use the same filters while switching between map-view and list-view 
- [x] Place filters on the same level as list-view/map-view buttons
- [x] Use GO primary color for the map legends 
- [x] Show the healthcare local units map legends only after selecting the Healthcare type from the filters
- [x] Open the edit Local Units modal when clicking on the local units title in the pop-up of map-view 
- [x] Add validate action on the list-view in a new column 
- [x] Remove validate button from the `...` options
- [x] Remove validate button from the list-view and `...` options for the users with no rights
- [x] Place the fields in the Local Units forms to match the order in the prototype 
- [ ] Add Delete button and Validate button in the Local Units form pop-up
- [x] Positioning of the list-view / map-view buttons
- [x] IFRCGo/go-api#2206

## TODO (mariam (Guest)8/19 9:19 PM)
- [x] The titles in the popups were cut off. We could show them all as it's hard to see much of it. Here is a suggestion with 2 lines. https://www.figma.com/design/k9SOqgh5jk9PxzuBKdMKsA/IFRC-GO---UI-Library?node-id=11253-185144&t=LTwsIaEgrUJA4U49-0
  - [x] Also, they should be links to the view mode. It is ok that the link is to an overlap and not a page. 
- [ ] Add an edit button within the View mode for the users who have such permissions, which will allow them to quick edit if needed (if this doesn't exist already): https://www.figma.com/design/myeW85ibN5p2SlnXcEpxFD/IFRC-GO---UI-Current---1?node-id=19627-191185&t=rf75rmgxk7GFQtE4-4
- [x] For validated (when the user doesn't have such permissions), here is the look we suggest - grey button: #C6C6C6
![Screenshot at Aug 11 22-04-46](https://github.com/user-attachments/assets/7a3a76a0-26c3-411f-9616-f78901907474)

**Comment by shraeyaa** [comment]
1.  Open the edit Local Units modal when clicking on the local units title in the pop-up of map-view
    - Needs to be done
2.  Add Delete button and Validate button in the Local Units form pop-up
    - The Figma contains the Delete and Validate button on the local units form pop-up
![image](https://github.com/IFRCGo/go-web-app/assets/54019619/8d3d8318-f623-46dc-9b20-021a1e53eebe)

cc @frozenhelium @udaynwa
