### ISSUE TITLE
Operational Learning Page: Integrate LLM summaries for Operational Learning

### ISSUE THREAD

**Issue by samshara** [IFRCGo/go-web-app#1218]
Operational learnings in emergencies are the lessons learned from managing and dealing with crises, refining protocols for resource allocation, decision-making, communication strategies, and much more.  The summaries are generated using AI and Large Language Models, based on data coming from Final DREF Reports, Emergency Appeal reports and others.
### Previous implementation
[extractor-operational-learnings](https://github.com/IFRCGo/extractor-operational-learnings)
### Frontend Tasks
- [x] IFRCGo/go-web-app#1219
- [x] IFRCGo/go-web-app#1220
- [x] IFRCGo/go-web-app#1221
- [x] IFRCGo/go-web-app#1222
- [x] IFRCGo/go-web-app#1223
- [x] IFRCGo/go-web-app#1224
- [x] IFRCGo/go-web-app#1225
- [x] IFRCGo/go-web-app#1226
- [x] IFRCGo/go-web-app#1252
- [x] IFRCGo/go-web-app#1362
- [x] IFRCGo/go-web-app#1363
- [x] IFRCGo/go-web-app#1364
- [x] #1378
- [x] #1379
- [x] #1381

### Backend Tasks

- [x] IFRCGo/go-api#2198
- [x] IFRCGo/go-api#2199
- [x] IFRCGo/go-api#2200
- [x] IFRCGo/go-api#2211
- [x] IFRCGo/go-api#2212
- [x] IFRCGo/go-api#2201
- [x] IFRCGo/go-api#2259
- [x] IFRCGo/go-api#2260
