### ISSUE TITLE
Minor fixes: June 26, 2024

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#1230]
## Description
- Reported by Justin in GO Risk Watch All Stars channel 

## TODO 

- [ ] default month when you land on the Country Risk Watch page goes to January rather than the current month
- [ ] we don't seem to be following the rounding rules consistently when showing the numbers in the tables. Thus, for Guatemala, the annual risk metrics look like this: 
   - [ ] ![Image](https://github.com/IFRCGo/go-web-app/assets/72339626/f9d068a9-8833-4fde-9d1a-96d4f9ce86f0)

**Comment by nanometrenat** [comment]
xref https://github.com/IFRCGo/go-api/issues/1272
