### ISSUE TITLE
Show cone of uncertainty, path, and affected areas for GDACS, WFP ADAM and PDC

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#1265]
## Task background 
We have the data related to the cone of uncertainty, path, and affected areas for GDACs, PDC, and WFP ADAM, but currently, we are not showing them in the Risk Module in the GO platform. 

## Behavioral and implementation details
- @puranban and @ranjan to add

### Development tickets 
- [x] IFRCGo/go-risk-module-api#9
- [x] IFRCGo/go-risk-module-api#10
- [x] IFRCGo/go-web-app#1295
- [x] IFRCGo/go-web-app#1296
- [x] #1297
- [x] #1345
- [x] #1346
- [x] #1347
- [x] #1348
- [x] #1349

### Review fixes (based on Justin and Mariam's review on 30.10.2024):
- [x] Map legend: Delete the word "Map" from "Map Sources" so that it just reads: "Sources"
- [x] In the pop-up box for GDACS storms, where it currently says "Source: [JTWC, or NOAA or other]" let's replace "Source:" with "Forecast provider:"
- [x] In the pop-up box for both PDC and for GDACS, replace "Exposed area" with "Exposed area to tropical storm or cyclone strength wind"
- [x] In the pop-up box for both PDC and GDACS where it says "Severity" : 1) first change the text to "PDC Severity" or "GDACS Severity"; and 2) add a tool tip with a link to the source
- [ ] In the colouring of the exposed area, does this apply to future exposure, past exposure or both? At the moment, it's unclear and we need to make it clear whether its one, the other or both. 
- [ ] For storm position (at a specific date and time) as denoted by dots: this is currently not working for either the PDC or GDACS events -- nothing happens when you click on the dots

**Comment by udaynwa** [comment]
Related to: #1013

**Comment by justinginnetti** [comment]
Feedback on GDACS tropical cyclones/storms:
- [x] Replace "Source:" with "Forecast Source:"
- [x] Replace "Alert Type:" with "GDACS Alert Level"
- [x] Replace "Track" with "Forecast track"
- [x] Replace "Buffer" with "Windspeed buffer"
- [x] Replace "Nodes" with "Position of storm"
- [x] Add the "time stamp" to each of the locations of the points (i.e., "nodes") related to the position of the storm
- [ ] For the "nodes" replace the triangles with the icon for the cyclone or just a dot if we can't do the icon
- [ ] To do: Find out from GDACS what the "track" represents (for example, the "most likely" track or something else?), and then we will have to update the label accordingly.
- [ ] Under the "buffers" toggle: Specify "GDACS Red Alert Level" "GDACS Orange Alert Level" and "GDACS Green Alert Level"

**Comment by puranban** [comment]
> Add the "time stamp" to each of the locations of the points (i.e., "nodes") related to the position of the storm

For this @justinginnetti , `trackdate` is missing in the current source. But there is seems to be another resources available in the GDACS system, so we will be trying to scrape the `trackdate` from there and soon update the cyclone timestamp in the visualization if it works.

> Under the "buffers" toggle: Specify "GDACS Red Alert Level" "GDACS Orange Alert Level" and "GDACS Green Alert Level"

I think this one conflicts with the earlier feedback where you mention `Replace "Alert Type:" with "GDACS Alert Level"`. Do we specify each alert level also as `GDACS Red Alert Level`, `GDACS Orange Alert Level` and such? 


Besides these, we have incorporate other mentioned feedback along with some more improvements **for GDACS,** and pushed it to the [Alpha 3 instance.](https://alpha-3.ifrc-go.dev.datafriendlyspace.org/risk-watch/imminent)

**Comment by udaynwa** [comment]
@justinginnetti @mariam-yu , replying to the requested review fixes: 

- In the pop-up box for both PDC and GDACS where it says "Severity" : 1) first change the text to "PDC Severity" or "GDACS Severity"; and 2) add a tool tip with a link to the source
  - We need to revisit the labels for GDACS and PDC 
We don't have "Severity" displayed on PDC
"Severity" in GDACS is showing wind speed / category instead.
"Alert Type" is actually showing "Alert Level" which is closer to "Severity"
- In the colouring of the exposed area, does this apply to future exposure, past exposure or both? At the moment, it's unclear and we need to make it clear whether its one, the other or both.
  - We do not have different exposures for future or past. We just have single exposure data that we fetch from GDACS, PDC
- For storm position (at a specific date and time) as denoted by dots: this is currently not working for either the PDC or GDACS events -- nothing happens when you click on the dots
  - Currently, we do not have much information from the sources to display on the popup  

cc @frozenhelium @tnagorra

**Comment by justinginnetti** [comment]
Let's have a quick, sync call on the pending items, @udaynwa just to triage which we can fix now, and which we will save for later.

**Comment by udaynwa** [comment]
Sure, @justinginnetti . Would you like to meet 30 minutes before GO check-in tomorrow?
