### ISSUE TITLE
DREF Import Issues (from QA Team)

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#1288]
## TODO

- [x] When clicked on YES for "Are there any mechanisms?" a description box pops up in the form, while there is no place for a description on the import file
![unnamed](https://github.com/user-attachments/assets/a639bbb5-1456-4bf6-95cf-6d391d74c89e)
![unnamed (1)](https://github.com/user-attachments/assets/f4eede31-b5df-4b2e-90d2-37171e5ba9f5)

- [x] Section Titles missing. eg: 'Objective and Strategy Rationale', 'Targeting Strategy' in the Operation tab
![Image](https://github.com/user-attachments/assets/29c4bf0a-6994-4f41-8187-b06854eea465)

- [x] In tab ‘Event Detail’ a field is missing when Yes is clicked for ‘Did the National Society request funding from DREF for that event(s)?’
![Image](https://github.com/user-attachments/assets/c42882cd-2531-4050-b270-cbb094be8882)
![Image](https://github.com/user-attachments/assets/26b9c339-529b-46fa-98c6-effc6e5b311b)

- [x] Section titles missing on the "Operational Timeframes and Contacts" tab as well

- [x] In the Actions/Needs tab, When clicked on Yes for ‘Has the National Society started any actions?’, a field pops up for ‘Start Date of National Society Actions’, but there is no field in the import file
![Image](https://github.com/user-attachments/assets/0ce1cf2e-6954-405b-80ff-c6096319aefc)
![Image](https://github.com/user-attachments/assets/de20bea8-0906-4d84-962d-bd47a45d8d8e)

- [x] Event Detail > Description of the Event - Field name is “Date when the trigger was met” in the DREF form while field name is “Date of the Event” in import template
![Image](https://github.com/user-attachments/assets/9f1da541-7c6d-41f9-b133-f903bb5b5fdd)
![Image](https://github.com/user-attachments/assets/3602df59-abd0-4cc2-9f82-054a680b73db)

- [x] In tab Actions/Needs > Needs (Gaps) Identified, the field name is displayed by ‘--’ in the form, after the file has been imported
![Image](https://github.com/user-attachments/assets/22eef26e-241a-4382-8d43-9553fd22155f)
- [x] All the numeric fields in the DREF form show this error while saving the form, when the numeric data has been imported from the template
![Image](https://github.com/user-attachments/assets/94b8d041-254d-4576-a29a-a2ecd612207f)
![Image](https://github.com/user-attachments/assets/222fbd9f-adfc-49ad-9139-4c723d255653)
![Image](https://github.com/user-attachments/assets/95485ffb-309c-431e-ab8f-a106226425a0)

**Comment by barshathakuri** [comment]
As per the modified template, we don't need tabs name heading in each tab.
