### ISSUE TITLE
Storybook design audit

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#1291]
# Audit document
- [GO - Storybook components audit - Jun 27 2024](https://docs.google.com/document/d/1M5pVE7MzvJn5wTBvGaioDZLrnn-QHv2mzhiexRXjG0k/edit#heading=h.ijcqvhvosnnk)

## Alert

- [ ] Remove the header
- [ ] Add a "x" button to close the alert
- [x] Dropshadow should be `box-shadow values: 0px 3px 8px rgba(0, 0, 0, 0.2)

### Info Alert

- [x] We are using Gray 80. Mariam suggests we use Gray 50

### Danger Alert

- [x] Icon does not match.

## Bar Chart

- [x] Left-side of the bar should not have a border radius

## Boolean Input

- [x] Text color should be IFRC/Black #000000
- [x] Unselected circle should be Grey 30 #C6C6C6

## Breadcrumbs

- [x] Text color should be IFRC/DarkGrey #323232
- [x] Arror icon does not match. (What should be the behavior when clicking on the icon?)
- [x] Last element must have font-weight: 500 and rest element must have font-weight: 300

> Review has been skipped for Breadcrumbs component.

## Button

- [x] Button should have 24px padding
- [x] Minimum length of button regardless of text should be 104px
- [x] Text frame should be 21px high and text aligned to middle (currently 17px)
- [x] Missing story: secondary button with icon
- [x] Missing story: primary button with icon
- [x] Missing story: tertiary button with icon
- [x] Missing story: gray tertiary button with icon
- [ ] Missing story: process button with icon

## Checkbox

- [x] Color should be Gray 30 #C6C6C6
- [x] Selected state should be inverted (red and white)

## ConfirmButton

- [ ] Disabled primary button should have background color Grey 30 #C6C6C6
- [x] The cancel button does not match the design - there should be a Tertiary Button (This requirement was moved from Modal)

## Date Input

- [ ] There should be a placeholder (not possible)
- [x] Input height should be 24px
- [ ] Padding should be 12px from the left edge for the label
- [ ] Padding should be 12px from the left edge for the text
- [x] There should be an icon (already there, depends on the browser)

## DropdownMenu

- [x] Height should be of 32px (currently 25px)
- [x] Side padding should be 24px instead of 16px
- [ ] There should not be a triange on the popup
- [x] The popup menu should have border radius of 4px
- [ ] Expanded list should have hover of color Gray10 #F2F2F2
- [x] Box shadow should be `box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.08)`

## Footer

- [x] Does not match completely (we need to investigate)

> Review has been skipped for Breadcrumbs component.

## Header (Page Header)

- [ ] The name and description of sizes and fonts do not match

```css
/* Header */
font-family: 'Poppins';
font-style: normal;
font-weight: 600;
font-size: 40px;
line-height: 60px;
/* identical to box height */
text-align: center;
letter-spacing: 1.6px;
```

```css
/* Header description */
/* Body/GO Text - Light 14px */
font-family: 'Poppins';
font-style: normal;
font-weight: 300;
font-size: 14px;
line-height: 21px;
text-align: center;
```

## IconButton

- [x] Missing story: a button an icon with no fill but with stroke

## InfoPopup

- [ ] The triangle should be exactly in the middle
- [x] Close "X" button is missing
- [x] The box shadow should be `rgba(0, 0, 0, 0.08)`
- [x] Title should be separated by a 1px line with color Gray20 #E0E0E0 having a top padding of 8px
- [x] Font weight should be 500px (most probably heading)

## LegendItem

- [x] Missing story: Icon is missing

## List

- [x] When data is not available should not have an icon.
- [x] Text "data is not available" should have whitespace of 200px height.
- [x] The description itself should have a top padding of 40px.

## Modal

- [x] Title font-weight should be 500
- [x] Title should be separated by 1px line with color Gray20 (#E0E0E0)
- [x] Cancel button does not match the design (there should be a tertiary button)
- [x] Width of standard modal should be 420px.

## MultiSelectInput

- [x] Selected options should not be kept inside the input?
- [x] Clear all button should be inside the popup as "Clear all".
- [ ] There is no search in an expanded list with lists of more than 10 elements?
- [ ] Expanded list should open downwards.
- [ ] Should not have triangle in the popup.
- [x] Box shadow should be `box-shadow: 0xp 0px 10p rgba(0, 0, 0, 0.08)`
- [x] Input height should be 24px
- [x] In disabled mode, there should not be an "x"

## NavigationTabList

- [ ] Usage is not clear for YU

## NumberInput

- [x] Labels and text should be aligned on the same vertical line
- [x] Height should be 32px

## PieChart

- [x] Missing white dividing lines between the section
- [x] Legends should have 8px space between each other
- [x] Text style does not match for legend

```css
/* Text style */
/* All caps - Regular 10px */
font-family: 'Poppins';
font-style: normal;
font-weight: 400;
font-size: 10px;
line-height: 15px;
/* identical to box height */
text-transform: uppercase;
/* IFRC/Dark Grey */
color: #323232;

```

### Error

- [x] YU has a completely different 404 page designed

## Popup

- [x] Dropshadow should be `box-shadow values: 0px 0px 10px rgba(0, 0, 0, 0.08)

## Progressbar

- [x] Border radius of left should be zero

## Radio Input

- [x] The color for default should be Grey 30 (#C6C6C6)

## RawFileInput

- [x] Button should be in form of secondary button with additional upload icon on the left side (We need to update the story)

### RawList

- [ ] Usage is not clear for YU

### ReducedListDisplay

- [ ] Usage is not clear for YU

### Segment Input

- [x] Unselected section should have a fill without a stroke (#F7F7F7)
- [ ] Description should be centered on each section

### Switch

- [x] Left and Right side should have completely round edges
- [ ] NOTE: Other designs are also different.

## Table

- [x] Story: Links should be black and hover should be IFRC/Red
- [x] Top and bottom line indents should be at least 12px?
- [ ] Table label color should be IFRC Grey 10 (#F2F2F2)

## Tab

> NOTE: Need to check NavigationTab as well

### Default

- [x] Selected tab should have 2px high underline IFRC Red (#F5333F)

### Secondary

- [x] Design has changed

### Step

- [x] A black line appears between the dots.
- [x] The line should be 2px high

## Text Area

- [x] Labels and text should be aligned on the same vertical line

## Text Input

- [x] Labels and text should be aligned on the same vertical line

## Tooltip

- [ ] Text style does not match.
- [x] There must be dividing line after the title
- [x] Box shadow should be `box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.08)`
- [x] Story: Add one without title

## Misc

- [ ] Each tab should be 280px wide
