### ISSUE TITLE
Enhancements for the import template (from Marco)

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#1306]
## TODO

- [x] For indicators, sources of information, risk and mitigation, increase options from 3 to 5. 
- [x] For the Timeframe and Contacts information section, please just leave the “Operational Timeframe” field, remove all others as they are completed at latest stages and not during the use of the offline template.  
- [x] In all section, double the width of the “Value” Cell to 128 pixels, so double, this works better for the long text format values.  
- [x] Is it possible to assign also lengths or high to the rows, row by row, so we have have a visual cue of which are the long format rows by having bigger cells space.  
- [x] Is it possible for the excel too always be formatted to adjust to text 
- [x] We need to have more separation between sections, like between the actions section and the needs section as well as to have more subtitles
  - [x] We need to add extra headings on the form.
  - [x] The borders are not set when the background is set.
  - [x] The template is also not consistent with the template provided. (content, color, tab color, font size, font color, etc.)
- [x] In excel, when adding “-“ or “=“ at the start of a cell, it things is a formula and gives an error, in some cases user will want to have “-‘ as bullet point to list activities and that could bring an error. Not sure of there is something to avoid that. 
  - [x] Add this as the description text of `List of Activities` field in `Operation` sheet: A list should start with an ' * ' followed by a space. There are no limits to the number of lists that can be included.
Eg: * Activity XYZ * Activity ABC (each one in new line)
- [x] Error while opening the file
- [x] Add all the missing fields in the modified template 
  - [x] `Date of the event` should be replaced with `Date when the trigger was met`
  - [x] ICRC > Actions Needs
  - [x] List coordination mechanisms/platform in place at local/district and national level. Indicate the lead authorities/agencies. How the National Society is involved/positioned in this coordination. Does the NS in any lead/co-lead role? Any identified gap/overlap in the coordination (e.g., sector missing…)?
  - [x] Date of Submission to GVA
  - [x] Date of Approval

## To be discussed

- [x] Currently if we set the height, the row does not auto grow. We need to look into alternative solutions.
- [x] We also need to discuss with Marco about consistent color for headings. What about heading levels more than 2-3? We currently already have headings on 5th levels. (make the list gray and alternate color use blue color only for headings).

**Comment by frozenhelium** [comment]
Hey @marcovvu1,

For the feedback
>For the Timeframe and Contacts information section, please just leave the “Operational Timeframe” field, remove all others as they are completed at latest stages and not during the use of the offline template.

Do you mean to,

1. Remove all other fields from the section **Operational Timeframes** and only keep the field `Operation timeframe`

Or,

2. Remove **Tracking data and contacts** section and only keep **Operational Timeframes** section.

It's a bit confusing due to the same name. Let us know which one is it.

CC: @udaynwa @tovari @anamariaescobar

**Comment by marcovvu1** [comment]
> Hey @marcovvu1,
> 
> 
> 
> For the feedback
> 
> >For the Timeframe and Contacts information section, please just leave the “Operational Timeframe” field, remove all others as they are completed at latest stages and not during the use of the offline template.
> 
> 
> 
> Do you mean to,
> 
> 
> 
> 1. Remove all other fields from the section **Operational Timeframes** and only keep the field `Operation timeframe`
> 
> 
> 
> Or,
> 
> 
> 
> 2. Remove **Tracking data and contacts** section and only keep **Operational Timeframes** section.
> 
> 
> 
> It's a bit confusing due to the same name. Let us know which one is it.
> 
> 
> 
> CC: @udaynwa @tovari @anamariaescobar 

Hi! 

We can keep the section lets say, the Operation timeframe section, but leave just the on question about the amount of months of the operation.

**Comment by frozenhelium** [comment]
> Hi!
> 
> We can keep the section lets say, the Operation timeframe section, but leave just the on question about the amount of months of the operation.

@marcovvu1 And remove the `Tracking data and contacts` section? Or keep it as well?

**Comment by udaynwa** [comment]
## Questions from Marco (20/9/24)

- date fields: how can we ensure that people always put the right format to ensure no issues in the import
- Column A: question on whether column A can be blocked from any editing, and if that would not impact collaborative work

cc @tovari @barshathakuri @frozenhelium @tnagorra @samshara

**Comment by udaynwa** [comment]
@marcovvu1 @tovari 

> date fields: how can we ensure that people always put the right format to ensure no issues in the import
- Any date format will be accepted. The import template will automatically convert the entered date into the correct format. For the unconvertible date, the import template gives an error pop-up. (screenshot attached)
![image](https://github.com/user-attachments/assets/87dae2ed-9729-427a-8937-1332001bc3c6)

> Column A: question on whether column A can be blocked from any editing, and if that would not impact collaborative work
- Implementing the blocking is not entirely possible. Microsoft Excel can override the implementation, so there is no straightforward way. 

cc @samshara @frozenhelium @barshathakuri
