### ISSUE TITLE
Update Field Report and Emergency Title Composition

### ISSUE THREAD

**Issue by samshara** [IFRCGo/go-web-app#1382]
fixes https://github.com/IFRCGo/go-web-app/issues/525#issuecomment-2118209813

- [x] IFRCGo/go-api#2265
- [x] IFRCGo/go-api#2266
- [x] IFRCGo/go-api#2354
- [x] IFRCGo/go-web-app#1385

**Comment by tovari** [comment]
Thanks, I see the following problems on Staging:
- the FR title is not cascading to the emergency title. Emergency page title should get the translated versions. Currently the emergency page title is in the original language regardless of the selected language
- Disaster type translations are not taken from the database at the moment, the english version is used at each language
- Arabic title component order is incorrect. It should be from right to left: ISO3 code - disaster type (in arabic) - date - custom string (in arabic) - #FR

**Comment by nanometrenat** [comment]
Hi there, just saw the above.  In terms of business logic, what happens when the emergency changes scale/location?  e.g. starts as a single-country event then enlarges to cover more countries (like Ukraine response, covid response, various migration responses), or starts as a single event then the appeal covers more (like the current Philippines response which started as Tropical Cyclone Kristine but now covers 6 typhoons)?  Need to make sure the autonaming can handle cases like this - even when edited.
I've not seen the business requirements so hopefully this is already in the requirements and test coverage.

Additionally, if using codes rather than full words, need to make sure the Search rules are updated to return the results expected by the user.

Thanks a million as always!

**Comment by tovari** [comment]
I see still a few things to fix:
- On the field report form, the title preview shows always the english disaster type, regardless of the page language
- The new emergency page original language is set always to english regardless of the FR original language
