### ISSUE TITLE
Add/Update guidance and implement visual changes in the DREF Import template

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#1431]
Check and implement the revised version of the import template with additional guidance and some visual changes. The file has been attached below: 

[20241022_DREF import_v2_KJM.xlsx](https://github.com/user-attachments/files/17502284/20241022_DREF.import_v2_KJM.xlsx)

#### TODO (in order of priority

- [x] Additional guidance provided to the questions
- [x] Additional visual changes 
- [x] Landing page/sheet

**Comment by udaynwa** [comment]
@marcovvu1 , @anamariaescobar , @tovari , the guidance updates, and visual changes have been implemented to the DREF Import template. Please review this latest import template file. Link: [DREF_Application_Response_import_template_29_10_2024._16_42_36.xlsx](https://github.com/user-attachments/files/17566601/DREF_Application_Response_import_template_29_10_2024._16_42_36.xlsx)

There were some inconsistencies in the import template which was shared with us. We have listed them in the `Questions` section of this PR. Link: https://github.com/IFRCGo/go-web-app/pull/1434
