### ISSUE TITLE
DREF Imminent returns!

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-web-app#1455]
We are ready to re-start the work, below you will find all the fields currently used in the DREF Imminent Application and how they map out to the new form:

**General Observations**
- [x] Tittle on the Export must be "Imminent DREF operation" instead of "DREF Operation"

**Operation Overview**
- [x] Emergency appeal planned: Hide this field
- [x] Upload map: Hide this field
- [x] Type of Onset: Let's keep this field but it should default to "Sudden", no option to be changed
- [x] Disaster Category: Hide this field
- [x] If available please upload Crisis categorization Analysis: Hide this field

**Event Detail** ---> Replace name with "Scenario Analysis"

- [x] Previous Operations: Hide the whole section
- [x] Description of the Event: Hide the whole section, only Total people at risk and Sources of information will remain visible
- [x] Add new question: When and where is the hazard expected to happen? : Guidance: Narrative including Date and geographical areas
- [x] Add new question: Explain the underlying vulnerabilities and risks the hazard poses for at-risk communities?  : Text. Guidance: Based on comparison of past events, what humanitarian impacts do you expect? Of what magnitude? (e.g. last time there was a cyclone making landfall with this windspeed, XX houses were destroyed, and we had to launch a DREF/emergency appeal for CHF xxx) 
- [x] Add new space to attach documents: Upload any additional support document (Optional)

**Action/Needs** ---> Hide the whole section

**Operation**
- [x] Hide the whole section, only "Total Targeted Population" section and "Will surge personnel be deployed?" will remain visible.
- [x] Add new space to attach documents: "If the National Society has developed contingency plans, or recently carried out PER assessment or readiness check for instance, kindly attached those documents here"
- [x] Add new question: Which of the expected severe humanitarian impacts of the hazard are your actions addressing? Why were these impacts chosen? --> Guidance: Prioritized impact of the foreseen disaster
- [x] Add new section: "Proposed actions", this section will be similar to "planned interventions" in the other forms, but the grouping wont be by sector (Shelter, Health, etc) but by type of intervention, there will be only two boxes, "Early Actions" and "Early Response", with Activities (we want to find a way to "tag" each one of the activities with sectors) and budget, some extra rows at the end, please see picture attached below (please note that the sub-total should be a sum of the budgets, it should ALWAYS total 75k, so we can add some logic and a warning if it is not matching)
![Image](https://github.com/user-attachments/assets/ad3b2e8c-a6f3-42d6-b653-71ac0406ceea)

**Operational Timeframes and Contacts**---> Stays the same, only hide the Glide number

@tovari @udaynwa @marcovvu1

**Comment by samshara** [comment]
@anamariaescobar We reviewed the requested changes, and most of these appear to be minor. 
However, we have some questions:

- When we say "hide," are we only hiding the field, or should it be removed entirely? If we're simply hiding it, this might mean the database continues to store fields that aren’t needed. If we decide to clean up these fields, we could lose previous data.

- Regarding the following:
> Add new section: "Proposed actions." This section will be similar to "planned interventions" in other forms, but the grouping will be by type of intervention (not by sector, e.g., Shelter, Health, etc.). It will have only two boxes, "Early Actions" and "Early Response," with Activities (we would like to "tag" each activity with sectors) and budget. Some additional rows at the end are required, as shown in the picture below (please note that the sub-total should sum the budgets to always total 75k. We could add logic and a warning if it doesn’t match.)

Should the Activities box be a text field where we can enter multiple sectors (text fields) with the budget for that box/column, or should it be broken down by individual sectors with a budget field for each? Also, do we need to link to actual sectors in GO, or is free text sufficient?

Also, do we need to include the "Surge deployment" and "Indirect cost" sections?

- Since we are modifying the entire form, have we considered the impact on the Operational Update and Final Report forms? Some fields that are hidden here may appear in these reports. Should the new fields also appear in the Operational Update and Final Report forms?

cc @tovari @marcovvu1 @tovari

**Comment by anamariaescobar** [comment]
Hello @samshara !!!

Here some answers to your questions:

- When we say "hide," are we only hiding the field, or should it be removed entirely? If we're simply hiding it, this might mean the database continues to store fields that aren’t needed. If we decide to clean up these fields, we could lose previous data. **We want to hide them, we don't want to loose the data we have collected so far for those fields, but it wont be needed going forward, is there a way we re-name those fields adding Deprecated or something like that?**

- Regarding the following:

_Add new section: "Proposed actions." This section will be similar to "planned interventions" in other forms, but the grouping will be by type of intervention (not by sector, e.g., Shelter, Health, etc.). It will have only two boxes, "Early Actions" and "Early Response," with Activities (we would like to "tag" each activity with sectors) and budget. Some additional rows at the end are required, as shown in the picture below (please note that the sub-total should sum the budgets to always total 75k. We could add logic and a warning if it doesn’t match.)_

Should the Activities box be a text field where we can enter multiple sectors (text fields) with the budget for that box/column, or should it be broken down by individual sectors with a budget field for each? Also, do we need to link to actual sectors in GO, or is free text sufficient? **I think for this one we might want to have one field for the activity and a corresponding field for the sector (which yes, it should link to the actual sectors we have in GO) and then have the ability to add another activity with their corresponding sector (like in the risk section we have for other DREF applications, instead of having a big blank text box**

- Also, do we need to include the "Surge deployment" and "Indirect cost" sections? **Surge deployment should appear and ALWAYS be 10k if the answer to Surge deployment under the Operation section is set to yes. Indirect costs will always appear and it will always be 5k if surge question is no, and 5,8k if the answer is yes**

- Since we are modifying the entire form, have we considered the impact on the Operational Update and Final Report forms? Some fields that are hidden here may appear in these reports. Should the new fields also appear in the Operational Update and Final Report forms? **With this new Imminent form there will be no Operational Update for Imminent, the only Operational Update will be to change the operation to a response, we will make some mapping to se what fields can be prepopulated from the Application. For the final report, we will post another ticket with the requirements.**

We do need to discuss how are we going to handle the transition time, when we launch this new imminent form we need to block the previous one, but if there is any imminent operations that began before the launch, they should continue with the previous behavior and forms, I think it would be useful to set up a call to discuss this, let me know what you think?

One more thing that I forgot to add on the previous ticket:

- [x] We need a new additional export, which will be the regular export plus the 2 las pages of the document attached (so the user will have the option to download just the export or the export+PGA whichc is including the last 2 pages).
[Imminent DREF request.docx](https://github.com/user-attachments/files/17722933/Imminent.DREF.request.docx)

@samshara @tovari @marcovvu1

**Comment by udaynwa** [comment]
Hey @anamariaescobar , @marcovvu1 , we have a question:

- We do have some new field additions in different sections of the form. Can you tell us which field is to be added in which section and sub-section of the form? 
  - EVENT DETAIL
    - Add new question: When and where is the hazard expected to happen? : Guidance: Narrative including Date and geographical areas
    - Add new question: Explain the underlying vulnerabilities and risks the hazard poses for at-risk communities? : Text. Guidance: Based on comparison of past events, what humanitarian impacts do you expect? Of what magnitude? (e.g. last time there was a cyclone making landfall with this windspeed, XX houses were destroyed, and we had to launch a DREF/emergency appeal for CHF xxx)
    - Add new space to attach documents: Upload any additional support document (Optional)
  - OPERATION
    - Add new space to attach documents: "If the National Society has developed contingency plans, or recently carried out PER assessment or readiness check for instance, kindly attached those documents here"
    - Add new question: Which of the expected severe humanitarian impacts of the hazard are your actions addressing? Why were these impacts chosen? --> Guidance: Prioritized impact of the foreseen disaster
    - Add new section: "Proposed actions", this section will be similar to "planned interventions" in the other forms, but the grouping wont be by sector (Shelter, Health, etc) but by type of intervention, there will be only two boxes, "Early Actions" and "Early Response", with Activities (we want to find a way to "tag" each one of the activities with sectors) and budget, some extra rows at the end, please see picture attached below (please note that the sub-total should be a sum of the budgets, it should ALWAYS total 75k, so we can add some logic and a warning if it is not matching)

cc @tovari @samshara @shreeyash07 @anamariaescobar @shraeyaa

**Comment by anamariaescobar** [comment]
Hey @udaynwa !!

yes, those new fields should go on those sections, that now we are going to re-name as:

*Scenario analysis*

- Add new question: When and where is the hazard expected to happen? : Guidance: Narrative including Date and geographical areas
- Add new question: Explain the underlying vulnerabilities and risks the hazard poses for at-risk communities? : Text. Guidance: Based on comparison of past events, what humanitarian impacts do you expect? Of what magnitude? (e.g. last time there was a cyclone making landfall with this windspeed, XX houses were destroyed, and we had to launch a DREF/emergency appeal for CHF xxx)
- Add new space to attach documents: Upload any additional support document (Optional)

*Plan*

- Add new space to attach documents: "If the National Society has developed contingency plans, or recently carried out PER assessment or readiness check for instance, kindly attached those documents here"
- Add new question: Which of the expected severe humanitarian impacts of the hazard are your actions addressing? Why were these impacts chosen? --> Guidance: Prioritized impact of the foreseen disaster
- Add new section: "Proposed actions", this section will be similar to "planned interventions" in the other forms, but the grouping wont be by sector (Shelter, Health, etc) but by type of intervention, there will be only two boxes, "Early Actions" and "Early Response", with Activities (we want to find a way to "tag" each one of the activities with sectors) and budget, some extra rows at the end, please see picture attached below (please note that the sub-total should be a sum of the budgets, it should ALWAYS total 75k, so we can add some logic and a warning if it is not matching)

Let me know if you have more questions!!

@tovari @samshara @shreeyash07 @shraeyaa

**Comment by udaynwa** [comment]
Thank you, @anamariaescobar . A couple of follow-up questions: 

So the new sections will look like this, right? 
<img width="842" alt="Image" src="https://github.com/user-attachments/assets/97a48222-a1f6-4703-910c-bfdaaaa96dd0" />


- For the **_Scenario Analysis_** section, all the new fields will go under the `Description of the Event` sub-section. Can you please confirm? 
- For the **_Plan_** section, which sub-section will the new fields go under?

**Comment by anamariaescobar** [comment]
@udaynwa there is no need for subsections, the form is too short, with the big sections (Operation Overview, Scenario, Plan etc) is enough

**Comment by anamariaescobar** [comment]
@udaynwa @samshara the form looks great!!! Some feedback from our side:

**Form in GO**

- [x] Scenario Analysis section, move the "sources of information" under "Explain the underlying vulnerabilities and risks the hazard poses for at-risk communities?"
- [x] Operational timeframe and contacts, the field "IFRC focal point for the emergency:" to be changed to "IFRC focal point for the operation" 
- [x] Scenario Analysis, Numeric detail, Total population at risk, add "(if available)"
- [x] Scenario Analysis, When and where is the hazard expected to happen?, let's change this one to "When is the hazard expected to happen?" and make it a date field
- [x] Plan, Total targeted population, hide this whole section
- [x] Below "Early Actions" and also for "Early Response" add a field for "Budget" (We want to move away from having budget per Activity and just have it for these big sections)
- [x] Plan, Proposed Actions, for both (Early Actions and Early response), for the dropdown change from "Select the Activity" for "Select the sector", change the header of the first textbox from "Activity" to "Sector", change "Budget" for "Activities" and change the numeric field to a bigger textbox with bullet points to list the activities.
- [x] Operational Timeframes and Contacts, Operation Timeframe, it will ALWAYS be 45 days, the user shouldn't be able to change it.
- [x] Operational Timeframes and Contacts, End date of Operation, it should remain being automatically calculated using the Date of Approval + Operation timeframe (always 45 days)


**Export**

- [x] Make the GO logo at the bottom a little bit bigger
- [x] In the first page, below the cover image, the summary information should look like this, I made a mapping of the fields from the form:

![Image](https://github.com/user-attachments/assets/d2981967-087e-40eb-8563-fa3c1bce3d07)
- Appeal: Appeal Code
- DREF Allocated: Plan, Proposed Actions, Total
- Hazard: Type of Hazard
- Country: Add Country
- People at risk (if available): Total population at risk
- Start date: Date of Approval
- End date: End date of Operation
- Event Onset: Always Sudden
- Forecasted day of event (or peak): When is the hazard expected to happen? 
- Operation Timeframe: Operation timeframe (always 45 days)
- Targeted Areas: Region/Province
- [x] Scenario analysis, "When and where is the hazard expected to happen?", combine "When is the hazard expected to happen?" and "Region/Province", remove "(Date and geographical area)"
- [x] Scenario analysis, "Source Information", remove the tittle, just leave the table
- [x] Plan, remove "If the National Society has developed contingency plans, or recently carried out PER assessment or readiness check for instance, kindly attached those documents to the request."
- [x] Plan, make sure if the option is marked as NO in the form, this question will not appear in the export
- [x] Plan, proposed actions, it should look like this:

![Image](https://github.com/user-attachments/assets/b7ab119f-d932-479c-85d7-8d2913ff4b4e)

- [x] On the "Imminent DREF Request and Obligations", "Bank details of the National Society", "Amount(CHF)", this field should be populated by the field: Plan, Proposed Actions, Total.

Do let me know if you would want to have a meeting to clarify any of the points above, thanks for all the work!!!

@tovari

**Comment by samshara** [comment]
@anamariaescobar @tovari Thank you for the feedback. We have looked into it. Everything looks good. We have few questions:
> Scenario analysis, "When and where is the hazard expected to happen?", combine "When is the hazard expected to happen?" and "Region/Province", remove "(Date and geographical area)"

This is a bit unclear. Can you please clarify? 
> Operational Timeframes and Contacts, Operation Timeframe, it will ALWAYS be 45 days, the user shouldn't be able to change it.

On the above, we are using months right now, we will multiply the existing data with 30 to get equivalent days. Is this logic correct?

Also, we need the icons for the Early actions and Early response.

**Comment by anamariaescobar** [comment]
@samshara sure!

> Scenario analysis, "When and where is the hazard expected to happen?", combine "When is the hazard expected to happen?" and "Region/Province", remove "(Date and geographical area)"
This is a bit unclear. Can you please clarify?

We want to change the question "When and where is the hazard expected to happen?" to ""When is the hazard expected to happen" and make it a date field (is already on the ticket), this is because we already have the the targeted areas in the field "Region/Province", but in the export we still want to see "When and where is the hazard expected to happen" and the answer would be a combination of both, does that clarify a little bit more?

> Operational Timeframes and Contacts, Operation Timeframe, it will ALWAYS be 45 days, the user shouldn't be able to change it.
On the above, we are using months right now, we will multiply the existing data with 30 to get equivalent days. Is this logic correct?

Hmmmm now is me who is confused jajajajjajaja, ideally that field "Operation Timeframe" will show 45 days on the form and on the export, and the end date would be the "Date of Approval" + 45 days and then default to end of that month, so if we do "Date of Approval"+2 months that will work!

Do let me know if you think maybe a call is needed!

@tovari @udaynwa

**Comment by samshara** [comment]
@anamariaescobar 
> We want to change the question "When and where is the hazard expected to happen?" to ""When is the hazard expected to happen" and make it a date field (is already on the ticket), this is because we already have the the targeted areas in the field "Region/Province", but in the export we still want to see "When and where is the hazard expected to happen" and the answer would be a combination of both, does that clarify a little bit more?

It's clear now. Thanks.

> Hmmmm now is me who is confused jajajajjajaja, ideally that field "Operation Timeframe" will show 45 days on the form and on the export, and the end date would be the "Date of Approval" + 45 days and then default to end of that month, so if we do "Date of Approval"+2 months that will work!

We will set the `Operation Timeframe` to `45 days` and calculate the the end date as `Date of Approval + 45 days` and default to the end of that month.

**Comment by udaynwa** [comment]
@anamariaescobar , one quick question: 

> Plan, Total targeted population, hide this whole section

For this, are we hiding this whole section shown in the screenshot? One thing to note: Currently, `Numbers of persons targeted with early actions (if any)` field only appears when the DREF type is Imminet. 
![Image](https://github.com/user-attachments/assets/a4a10f22-03d1-4902-8bf7-d3733072a315)

**Comment by udaynwa** [comment]
@anamariaescobar , 

> Operational Timeframes and Contacts, Operation Timeframe, it will ALWAYS be 45 days, the user shouldn't be able to change it.

We need your confirmation on this. Can you confirm if we can keep the `Operation Timeframe` as months? If so, for DREF Imminent, we will set it to 2 months in the form, and to calculate the `End date of operation`, we will not be using this field. Instead, we will add +45 days to the `Date of Approval`. Will this flow work? If not, we will need to have a discussion.

**Comment by anamariaescobar** [comment]
Hi @udaynwa !!!

Some answers to your questions:

> Plan, Total targeted population, hide this whole section

> For this, are we hiding this whole section shown in the screenshot? One thing to note: Currently, Numbers of persons targeted with early actions (if any) field only appears when the DREF type is Imminet.

Yes, we want to hide the whole section.

> Operational Timeframes and Contacts, Operation Timeframe, it will ALWAYS be 45 days, the user shouldn't be able to change it.

> We need your confirmation on this. Can you confirm if we can keep the Operation Timeframe as months? If so, for DREF Imminent, we will set it to 2 months in the form, and to calculate the End date of operation, we will not be using this field. Instead, we will add +45 days to the Date of Approval. Will this flow work? If not, we will need to have a discussion.

We need to show the 45 days in the form and the export, and then add the +45 days to the start date and default the end date to the last day of the month. Do let me know if we need to have a conversation on this.

**Comment by anamariaescobar** [comment]
Hi @udaynwa , you were right, we do want the free text for the list of Activities, so the way that you have it in Alpha-2 is correct! Sorry for the confusion.
I am adding here the icons: 

![Image](https://github.com/user-attachments/assets/7854f604-9983-4163-9c3e-a7c07908c503)

![Image](https://github.com/user-attachments/assets/8355017b-b7cd-4457-a21e-465b03127363)

Thanks!!

@samshara

**Comment by mariam-yu** [comment]
@anamariaescobar @udaynwa @samshara I think you guys got your icons already, but in any case this is the review our designer has done of existing icons. Let me know if any you need, and I'll send the svg. (cc @tovari )

![Image](https://github.com/user-attachments/assets/49647fa2-2ffc-44e9-a17d-618b60e52023)

**Comment by anamariaescobar** [comment]
The Imminent looks great!!! Thank you for the hard work!! Just a couple of comments from the DREF team:

- [x] "When is the hazard expected to happen?" - super minor, but would it be possible to grey out/make it impossible to select past dates?
- [x] In the form, areas are called "At risk areas", while in the PDF export, it's under "Targeted area". Can we named them "Targeted Areas" in both the export and the form?

@udaynwa @samshara @tovari

**Comment by udaynwa** [comment]
@anamariaescobar - The comments you posted on March 21 have been implemented and pushed to the Alpha-2 instance. I request you to verify them. 

Link: https://alpha-2.ifrc-go.dev.datafriendlyspace.org/

cc @tovari @samshara

**Comment by anamariaescobar** [comment]
@udaynwa some comments:

- [x] Changes to the Superticket 2.0 will be implemented for the Imminent when applicable?
- [x] Proposed Actions (in the Export) The Early Actions and Early Response shouldn't have a break between sectors, same with the budget, see picture below:

![Image](https://github.com/user-attachments/assets/39a27eef-52e5-4346-a909-2c25d52277b7)

- [x] If Surge is not being deployed, can we hide the surge field from the export? (Proposed Actions section)

![Image](https://github.com/user-attachments/assets/06df50c5-e04f-4d94-92db-de90b699597d)

- [x] Proposed Actions (export), can we have the names of the sectors, the Activities and the budget not in bold? (Keep the tittles and the Early Actions and Early Response in bold)
- [x] Proposed Actions (export), since que are removing the break lines, can we make the icons a bit bigger and move the names (Early Actions and Early Response) below the icons? Also, could we center the budget (since we are also removing the break lines)

@tovari @samshara

**Comment by samshara** [comment]
@anamariaescobar 
> Changes to the Superticket 2.0 will be implemented for the Imminent when applicable?

Yes, that will be the case once both changes are deployed. However, if they're deployed separately, there may be a period where only one of them is available.

**Comment by anamariaescobar** [comment]
@samshara, you mean both Supertickets 2.0 (Enhancements and Bugs), right? So am I correct on thinking that we would want to deploy those 2 before deploying this Imminent changes? (if that is the case, I think we are fine!)

I forgot one important feedback:

- [x] When creating an Ops Update from an Imminent Application, I love the pop up, can we change the wording to: "By creating an Operational Update the DREF Type needs to be changed. Are you sure?" If NO is selected, No Ops. Update should be created, if YES is selected, create the Ops. Update and default the Type to Response (allowing the user to change it to other types, EXCEPT Imminent)
- [x] Event Details --> Description of the Event --> Numeric details --> Change "Estimated male" for "Estimated male affected", "Estimated female" for "Estimated female affected"
- [x] Event Details --> Description of the Event --> Numeric details --> Can we have instead than only one field called "Estimated minors" have two fields named "Estimated Girls (under 18)" affected" and "Estimated Boys (under 18)"

@udaynwa @tovari

**Comment by samshara** [comment]
@anamariaescobar ,  
> you mean both Supertickets 2.0 (Enhancements and Bugs), right? So am I correct on thinking that we would want to deploy those 2 before deploying this Imminent changes? (if that is the case, I think we are fine!)

Yes, we will need to deploy these ahead of the imminent changes.

**Comment by frozenhelium** [comment]
@anamariaescobar 

>When creating an Ops Update from an Imminent Application, I love the pop up, can we change the wording to: "By creating an Operational Update the DREF Type needs to be changed. Are you sure?" If NO is selected, No Ops. Update should be created, if YES is selected, create the Ops. Update and default the Type to Response (allowing the user to change it to other types, EXCEPT Imminent)

What should be the behavior for existing operational update with Imminent type?

1. Migrate them to Response type (might result in some data loss)
2. When user edits it, change it to Response and show a pop-up to the user
3. Something else

**Comment by frozenhelium** [comment]
Going with option 2, as suggested by @anamariaescobar. CC: @udaynwa 

![Image](https://github.com/user-attachments/assets/fc19828a-88ec-4a89-96a7-663827bd12cc)

**Comment by udaynwa** [comment]
@anamariaescobar , we currently have DREF Final Reports with Immient type too. Due to this, these DREF Final Reports are getting `?` in the `Type of DREF` field (see attached screenshot). 

To resolve this, we need to implement a pop-up that prompts the user to change the type to "Response," similar to what we did in a prior comment. Should we proceed with this? 

![Image](https://github.com/user-attachments/assets/d6df494d-89c7-484d-b592-f3a67e6ab996)

cc @tovari @frozenhelium
