### ISSUE TITLE
Design audit items

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#319]
This is a list of items to be improved, reported in the staging audit by YU:
https://docs.google.com/document/d/1lwOeYkeOasYQlrILpS51KNoQivdX43Qr1VHvDo7Bd0c/edit#heading=h.3wreak3fwz2d

Please check the document for more detail about each item.

High priority:
- [ ] #351 
- [ ] #385
- [ ] #386

Medium priority:
- [ ] #387
- [ ] #388
- [ ] #389
- [ ] #390
- [ ] Main nav items - distance of items - Main nav
- [ ] Main nav- search bar styling - Main nav
- [ ] Nav item hovers and interactions - Main nav
- [ ] Country dropdown style - Main nav
- [ ] Dropdown height - Main nav
- [ ] Cards: styling - Components
- [ ] Tabs: styling - Components
- [ ] Dropdown: styling - Components
- [ ] Tables: sorting icon styling - Components
- [ ] External links: styling (country pages) - Componets
- [ ] Tooltip: interaction - Components
- [ ] Highlighted emergency cards: style - Components
- [ ] Key numbers: style - Components
- [ ] Section headers: style - Components

Low priority
- [ ] Map data points - crisis categorisation - Homepage
- [ ] Map Legends: styling - Components
- [ ] Filters: styling - Components
- [ ] Primary button: styling - Components
- [ ] Secondary button: styling - Components
- [ ] Pagination: styling - Components
- [ ] Breadcrumbs: styling - Components
- [ ] Checkbox: styling - Components
- [ ] Map: style - Components
- [ ] Side menu: style - Components
- [ ] Info cards on “Surge”: style - Component
- [ ] Side panel by the map: style - Component
- [ ] Data is not available! - Component
- [ ] Popup: style - Component

cc: @mariam-yu
