### ISSUE TITLE
Risk Watch updates Q4 2023 – Q1 2024

### ISSUE THREAD

**Issue by justinginnetti** [IFRCGo/go-web-app#326]
## Description of the ticket
This Risk Watch ticket contains a number of hot fixes to address issues related to the GO rewrite as well as the introduction of several new features, some of which are related to the Montandon-GO integration.

### Hot Fixes (Highest priority)

- [x] Risk information for certain hazards is not appearing on global/regional pages (applies to many countries, not only the DRC):
<img width="1343" alt="Screenshot 2023-12-05 at 11 43 05" src="https://github.com/IFRCGo/go-web-app/assets/74773708/cdbb083f-c537-4e07-933b-be85ad8b5ff0">
and
<img width="1405" alt="Screenshot 2023-12-05 at 11 46 56" src="https://github.com/IFRCGo/go-web-app/assets/74773708/64ce6d4e-c241-4866-91cb-2b0cb6196aae">

- [x] Risk information for an entire region (here Africa) is showing up on the bar chart:
<img width="1410" alt="Screenshot 2023-12-05 at 11 54 44" src="https://github.com/IFRCGo/go-web-app/assets/74773708/7f4b6bea-5a28-4c9a-b149-503cd4ae3d8a">

- [x] #453

- [x] Normalisation and coping capacity features not working on global and regional pages (seasonal risk tab): when you toggle those on and off, the bar charts do not update.

- [x] Missing information on global/regional pages: When only "flood" hazard is selected, the results look like an alphabetical list of countries and not a ranking of risk (see screenshot below):
<img width="1400" alt="Mystery of mysteries" src="https://github.com/IFRCGo/go-web-app/assets/74773708/7697b296-4834-4dab-accd-8fdc2e59c827">

- [x] #454

- [x] GDACS Imminent Event forecasts: In the pop-up box just have one link "More information" which would (in this case) redirect to the GDACS report (e.g., https://www.gdacs.org/report.aspx?eventid=1102364&episodeid=1&eventtype=FL). In other words, remove the URLs/links associated with what is currently shown for "More Details" and "Geometry" -- just keep the link for what is currently show as "Report" and rename "Report" as "More information"

- [x] No imminent event forecasted. When there is no imminent event forecasted, remove the map on the country page altogether; if that is too difficult, then replace the text with "No imminent event forecasted" but don't ever show this:
<img width="1415" alt="No Imminent Events" src="https://github.com/IFRCGo/go-web-app/assets/74773708/1dd27100-db43-4b3c-bbca-791b9b8a5934">
