### ISSUE TITLE
Workplan - Add to the "Supported by" listbox with options

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#451]
### User Stories
1. The user should be able to select a `Supported by` field in the PER Workplan
2. The user should be able to select a national society when `Supported by` is `National Society`

### Functional Requirements

- [x] #772
- [x] IFRCGo/go-api#1997
    - The supported by field has the following options
        1. UN Organization
        2. Private Sector
        3. Government
        4. National Society
     - Update API to fetch these types
     -  Migrate old data 
- The Frontend should allow the selection of  `Supported by organization type` 
- The Frontend should allow the selection of a `National Society` when `Supported by organization type` is `National Society` 

### Old title
Workplan - Add to the "Supported by" list box the following options: "IFRC, ICRC, UN organization, private sector, government"

**Comment by shraeyaa** [comment]
- [x] The options in the "Supported by" dropdown is not selected when clicked once. The options should be clicked on again to select it.
- [x] The export is successful only when there is no data in 'Workplan' tab, else shows server error.
- [x] On the PER forms list in Account section, fix the spelling of 'Accountability'. It is 'Accoutability' now
![image](https://github.com/IFRCGo/go-web-app/assets/54019619/ea8b014c-53d7-49ef-8178-76fafab08957)


cc: @barshathakuri @k9845

**Comment by udaynwa** [comment]
- [x] In the `Workplan` form, the user is not able to save the form after clearing the previously entered data from all the fields. The users should be able to save the form. 

cc @barshathakuri , @k9845
