### ISSUE TITLE
Country Pages re-vamp

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#492]
# Ticket description
Parent ticket for Country Pages re-vamp work item

### From QA team
- [x] IFRCGo/go-web-app#493
- [x] IFRCGo/go-web-app#494
- [x] IFRCGo/go-web-app#495
- [x] IFRCGo/go-web-app#496
- [x] IFRCGo/go-web-app#497
- [x] IFRCGo/go-web-app#498
- [ ] IFRCGo/go-web-app#499
- [x] IFRCGo/go-web-app#500
- [x] IFRCGo/go-web-app#554
- [x] IFRCGo/go-web-app#571 
- [x] IFRCGo/go-web-app#792

### Development tasks
- [x] IFRCGo/go-web-app#501
- [x] IFRCGo/go-web-app#502
- [x] IFRCGo/go-web-app#506
- [x] IFRCGo/go-web-app#550
- [x] IFRCGo/go-web-app#551
- [x] IFRCGo/go-web-app#552
- [x] IFRCGo/go-api#2039
- [x] IFRCGo/go-web-app#732
- [x] IFRCGo/go-web-app#747
- [x] IFRCGo/go-web-app#748
- [x] IFRCGo/go-api#2080

### Other tickets

External data exploration findings documentation:
- [x] IFRCGo/go-web-app#333 

Ticket to collect feedback from IM team:
- [x] IFRCGo/go-web-app#360 

Data validation test:
- [x] IFRCGo/go-web-app#541

Changes and additions documentation:
- [x] IFRCGo/go-web-app#610

**Comment by tovari** [comment]
Based on the review on the nightly server:
Ongoing activities:
- [x] Note the text alignment

Ongoing emergencies:
- [x] Filter at Operations Map should filter the list of operations as well. Don't need filter above the list.
- [x] Provinces filters doesn't make sense at the moment - should be removed

3W Activities:
- [x] Activities tab will need to be removed for now (See message on Teams in Country pages channel) 


National Society Overview
- [x] Note the text alignment

NS Activities
- [x] NS International Work - looks like projects stay in 'ongoing' status after end date. It should be closed after the end date. - Maybe this is only on the DFS server?


Context and Structure
- [x] Income Source Breakdown - ICRC and IFRC should be capitalized
- [ ] Key Documents - File names on the lists are not equal to the pdf title (e.g. AR_UnitedKingdom_2009.pdf when opened, the file name is Anual Report UnitedKingdom 2009.pdf)
- [x] FRDS should be FDRS at the bottom of the page

Strategic Priorities:
- [x] NS Country plan is missing (e.g. https://go-web-ifrc.dev.datafriendlyspace.org/countries/51/ns-overview/strategic-priorities), I see only NS Internal Plans

Country Profile
Supporting partners:
- [x] 'Go to IFRC.org' should be the button label

**Comment by udaynwa** [comment]
> Based on the review on the nightly server: Ongoing activities:
> 
> * [ ]  Note the text alignment
> 
> Ongoing emergencies:
> 
> * [ ]  Filter at Operations Map should filter the list of operations as well. Don't need filter above the list.
> * [ ]  Provinces filters doesn't make sense at the moment - should be removed
> 
> 3W Activities:
> 
> * [ ]  Activities tab will need to be removed for now (See message on Teams in Country pages channel)
> 
> National Society Overview
> 
> * [ ]  Note the text alignment
> 
> NS Activities
> 
> * [ ]  NS International Work - looks like projects stay in 'ongoing' status after end date. It should be closed after the end date. - Maybe this is only on the DFS server?
> 
> Context and Structure
> 
> * [ ]  Income Source Breakdown - ICRC and IFRC should be capitalized
> * [ ]  Key Documents - File names on the lists are not equal to the pdf title (e.g. AR_UnitedKingdom_2009.pdf when opened, the file name is Anual Report UnitedKingdom 2009.pdf)
> * [ ]  FRDS should be FDRS at the bottom of the page
> 
> Strategic Priorities:
> 
> * [ ]  NS Country plan is missing (e.g. https://go-web-ifrc.dev.datafriendlyspace.org/countries/51/ns-overview/strategic-priorities), I see only NS Internal Plans
> 
> Country Profile Supporting partners:
> 
> * [ ]  'Go to IFRC.org' should be the button label

Feedback moved to #360

**Comment by udaynwa** [comment]
Feedback in the comment above moved to IFRCGo/go-web-app#360
