### ISSUE TITLE
When Alerts are "Closed" we should change the start date from "Immediately" to the day the alert was closed

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#512]
based on https://github.com/IFRCGo/go-web-app/issues/512#issuecomment-1920782628

- [x] IFRCGo/go-web-app#555

based on https://github.com/IFRCGo/go-web-app/issues/512#issuecomment-1923542277
- [x] IFRCGo/go-web-app#572

based on https://github.com/IFRCGo/go-web-app/issues/512#issuecomment-1921415009
- [x] #581

based on https://github.com/IFRCGo/go-web-app/issues/512#issuecomment-1931792776
 - [x] IFRCGo/go-api#2036

**Comment by samshara** [comment]
@anamariaescobar , right now we have the following  date fields in the API

- `created_at`
- `start`
- `end`
- `opens`
- `closes`
![image](https://github.com/IFRCGo/go-web-app/assets/10930537/46e00507-e6c1-46f3-b933-93a7492a0ea5)

Here the fields to ui mapping is
- `created_at` -> `Alert Date`
- `duration` -> `end` - `start`

- For `Start Date` 
  - if `alert` is `closed` then show the `end` date
  - if `alert` is `open` and `start` is a date earlier than today show `Immediately`
  - if `alert` is `open` and `start` is a date later than today show the `start` date
- For `status`
  - if `alert` is `stood_down` show `Stood Down`
  - if `end` is earlier than today show `Closed` else show `Open`
  
 Questions

- Is the above mapping valid?
- What is the difference between `start`, `end` and `opens`, `closes`? What do they signify?
- We have missing data for some or all of the above fields for each `alert`, this leads to `--` being shown in the UI. Any idea why we are getting missing values?

cc @tovari

**Comment by anamariaescobar** [comment]
@samshara some answers to your questions:

- **Is the above mapping valid?** Only one thing I would change: if alert is closed then show the start date, not the end date.
- **What is the difference between start, end and opens, closes? What do they signify?** So, the open and closes are the dates when the alert is open and closes, which means when people can apply for it, the start and end date is when the deployment is expected to happen, so people who is going to apply can check their availability in those dates.
- **We have missing data for some or all of the above fields for each alert, this leads to -- being shown in the UI. Any idea why we are getting missing values?** - Yes! there was a historical data upload of deployments on the Molnix side, this created one "fake alert" per each deployment (more than 1000), we are already working on filtering out this alerts with @batpad and @szabozoltan69, so I would say don't worry about this point, but will let them confirm if any support from your side is needd.

**Comment by anamariaescobar** [comment]
@samshara I just realized there is two more thing we should change from the mapping:

- For status

> - if alert is stood_down shot Stood Down
> - if end is earlier than today show Closed else show Open --> Let's not use end, let's use closes for this one (closes will remain empty until the alerts is manually closed on the molnix side, so the logic still works, just not with end but with closes.

- created_at -> Alert Date --> Lets use start date for this field instead of created_at

We have run into two new problems, weirdly some start date for alerts are not coming through and the duration of the alert is not being calculated correctly, I have one example that I verified with the Surge team on Molnix:

![image](https://github.com/IFRCGo/go-web-app/assets/69478743/f0cd7b01-0f5d-4a09-b27f-477cb42a8f1e)
From Molnix we have star date: 31-01-24 and end date: 29-02-24, which will make duration 29 days.

@szabolcsgajerifrc @batpad @tovari

**Comment by samshara** [comment]
> created_at -> Alert Date --> Let's use start date for this field instead of created_at
@anamariaescobar , just to be clear we show the `start` date on the `Start Date` column as well. We have two columns
1. Alert Date 2. Start Date
If we show the `start` date for `Alert Date` column it means the `Start Date` column is somewhat redundant.
Maybe we could rename the columns to better reflect the information. Do you have any idea?
![image](https://github.com/IFRCGo/go-web-app/assets/10930537/46e00507-e6c1-46f3-b933-93a7492a0ea5)

**Comment by anamariaescobar** [comment]
Sorry, you are right!!! I meant using opens for the Alert date!!! @samshara

**Comment by samshara** [comment]
@anamariaescobar ,
For status
> If end is earlier than today show Closed else show Open --> Let's not use end, let's use closes for this one (closes will remain empty until the alerts is manually closed on the molnix side, so the logic still works, just not with end but with closes.

We are getting `null` values for the `closes` field for almost all of the data points. Is this normal?
If so, using it for calculating status would be difficult. Since we cannot compare it with any date. Or do we always show `Open` status for all the data points that don't have `closes`?

**Comment by anamariaescobar** [comment]
@samshara 

So, we have finally managed to remove the historical alerts (the ones coming without most of the dates), thanks to @szabozoltan69 and @batpad for the brilliant work on this one!

Now, we shouldn't have data point with null for the closes, but in case that happens, yes, let's categorize those alerts as open and I will take those issues with the Surge team because is probably an oversight from their part.

While looking into this issues, we have encounter another problem, there are some alerts that in the front end are not showing the start date:
![image](https://github.com/IFRCGo/go-web-app/assets/69478743/2bd7552e-6458-4ab5-9f7a-8c07cbcc673d)
this image is from this url: [Surge Global Overview](https://go.ifrc.org/surge/overview) (Open Surge Alerts section, page 2), we have double check wit Zoly and the date is indeed coming through to the backend:
![image](https://github.com/IFRCGo/go-web-app/assets/69478743/217f773a-d755-4ef4-90cd-54f4b466046e)
Can you take a look at this to figure out what is the issue here?
Also, seems like the sorting of the alerts is being done somehow related to dates, before the re-write we had implemented some rules, Open alerts will show on the top, followed by stood downs and then closed alert (if we think about the All surge alerts page), and then between the open alerts they will get sorted by alert date, do let me know if further clarification is need on this part.
Thanks!

**Comment by samshara** [comment]
@anamariaescobar , Thanks. We will look into the sorting issue as well.
