### ISSUE TITLE
Write stories for all UI components

### ISSUE THREAD

**Issue by samshara** [IFRCGo/go-web-app#583]
### Stories
- [x] https://github.com/IFRCGo/go-web-app/issues/579
- [x] https://github.com/IFRCGo/go-web-app/issues/578
- [x] https://github.com/IFRCGo/go-web-app/issues/577
- [x] https://github.com/IFRCGo/go-web-app/issues/576
- [x] https://github.com/IFRCGo/go-web-app/issues/575
- [x] https://github.com/IFRCGo/go-web-app/issues/600
- [x] https://github.com/IFRCGo/go-web-app/issues/599
- [x] https://github.com/IFRCGo/go-web-app/issues/623
- [x] https://github.com/IFRCGo/go-web-app/issues/622
- [x] https://github.com/IFRCGo/go-web-app/issues/601
- [x] #644 
- [x] #650
- [x] #652
- [x] #679
- [x] #678
- [x] #677
- [x] #683
- [x] #694 
- [x] #700
- [x] #703
- [x] #707
- [x] #712
- [x] #731
- [x] #722
- [x] #695
- [x] #716
- [x] #736
- [x] #944
- [x] #949
- [x] #950
- [x] #953
- [x] #960
- [x] #969
- [x] #966
- [x] #979
- [x] #956
- [x] #962
- [x] #989
- [x] #939
- [x] #986
- [x] #981
- [x] #1016
- [x] #1018
- [x] #1106
- [x] #1020
- [x] #1083
- [x] #1093
- [x] #1072
- [x] #1087
- [x] #1070
- [x] #1025
- [x] #1027
- [x] #1029
- [x] #1031
- [x] #1091
- [x] #1035
- [x] #1014
- [x] #1038
- [x] #1103
- [x] #1040
- [x] #1041
- [x] #1044
- [x] #1054
- [x] #1069
- [x] #1074
- [x] #1065
- [x] #1066
- [x] #1056
- [x] #1077
- [x] #1081
- [x] #1097
- [x] #1099
- [x] #1021

### Documentation
- [x] #586
- [x] #587

### Figma for UI components
https://www.figma.com/file/k9SOqgh5jk9PxzuBKdMKsA/IFRC-GO---UI-Library?type=design&node-id=11261-189642&mode=design&t=H77btqXhNDop8ZRl-0
