### ISSUE TITLE
KeyFigure Stories

### ISSUE THREAD

**Issue by shreeyash07** [IFRCGo/go-web-app#622]
## Task Description
   Create story for KeyFigure component

### Acceptance criteria
- [ ] KeyFigures should have icon and info section
- [ ] keyFigures should have NumberOutput
- [ ] KeyFigures should have Label and description
- [ ] KeyFigures should have ProgressBar
- [ ] KeyFigures should accept children 

#### Screenshots
![Image](https://github.com/IFRCGo/go-web-app/assets/45554490/1217ea40-7b52-4560-b8d0-1f686faf057c)

#### Links
  staging
     - https://go-stage.ifrc.org/dref-final-reports/43/edit
  Figma
    - https://www.figma.com/file/myeW85ibN5p2SlnXcEpxFD/IFRC-GO---UI-Current---1?type=design&node-id=0-4957&mode=design&t=KwxbuoUQxqcLyZbG-0
