### ISSUE TITLE
Container Stories

### ISSUE THREAD

**Issue by shreeyash07** [IFRCGo/go-web-app#623]
## Task Description
   Create story for Container component

### Acceptance criteria
- [ ] Container should have Header and header description
- [ ] Container should have Footer
- [ ] Container should have filters
- [ ] Container should accept children 

#### Screenshots
![Image](https://github.com/IFRCGo/go-web-app/assets/45554490/010aae69-50d7-4062-9ece-47564e858e40)

#### Links
  staging
     - https://go-stage.ifrc.org/dref-final-reports/43/edit
  Figma
    - https://www.figma.com/file/myeW85ibN5p2SlnXcEpxFD/IFRC-GO---UI-Current---1?type=design&node-id=0-4957&mode=design&t=KwxbuoUQxqcLyZbG-0
