### ISSUE TITLE
DREF Minor Issues

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#634]
## Tasks

- [x] IFRCGo/go-web-app#635
- [x] IFRCGo/go-web-app#636
- [x] IFRCGo/go-api#2050
- [x] IFRCGo/go-web-app#638
- [x] IFRCGo/go-web-app#639
