### ISSUE TITLE
DREF Operation Update > DREF Imminent Application to DREF Response Ops Update: Visibility updates

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#675]
## Task Description
Changes the visibility of the fields in the DREF Operational Update when DREF Imminent Application changes to DREF Response in Ops Update.

## Expected Behaviors
- [ ] Hide the following fields
   - **Event Details**
      - [ ] `Previous Operations`
      - [ ] `Upload any supporting documentation if relevant (Optional)`
    - **Operation**
       - [ ] Remove guidance in the `Planned intervention` field

- [ ] Unhide the following fields
  - **Operation Overview**
    - [ ] Disaster Category
    - [ ] If available, please update Crisis categorisation analysis.
    - [ ]  Emergency appeal planned.

  - **Event Details**
    - [ ] Date field called "Date of disaster"
    - [ ] Estimated population in need
    - [ ] Upload photos
 
  - **Actions/Needs** 
    - [ ] When did the National Society start responding?
    - [ ] Select the actions that apply
    - [ ] Any identified gaps/limitations in the assessment

## Acceptance Criteria
- [ ] All above mentioned fields should be hidden when DREF Imminent Application changes to DREF Response in Ops Update.
