### ISSUE TITLE
ExpandableContainer Stories

### ISSUE THREAD

**Issue by shreeyash07** [IFRCGo/go-web-app#694]
## Task Description
   Create story for Expandable Container component

### Acceptance criteria
- [ ] Expandable Container should have Header and header description
- [ ] Expandable Container should have Footer
- [ ] Expandable Container should have filters
- [ ] Expandable Container should accept children 
- [ ] Expandable Container should have expandable feature

##### On Container Close
![Image](https://github.com/IFRCGo/go-web-app/assets/45554490/f256e589-7112-41c1-a4c8-72ddd9554cbe)

##### On Container Open
![Image](https://github.com/IFRCGo/go-web-app/assets/45554490/51be3174-d2f1-4680-92c2-04603be18469)

#### Links
  staging
     - https://go-stage.ifrc.org/dref-final-reports/43/edit
  Figma
    - https://www.figma.com/file/myeW85ibN5p2SlnXcEpxFD/IFRC-GO---UI-Current---1?type=design&node-id=0-4957&mode=design&t=KwxbuoUQxqcLyZbG-0
