### ISSUE TITLE
DREF Application: Additions

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#698]
## Task description
List of new fields that are required to be added in the DREF Application when the DREF type is `Imminent`

## Expected behaviors
When the type of DREF is `Imminent`, the following new fields should be added to the DREF Application form:

### Event Details

- [x] `Threshold for early action:`
  - [x] `Threshold for early action:` field should have the guidance text: `A threshold is a value or a combination of values from which it is considered that the hazard will cause major humanitarian impact, such as an amount of rainfall combined with a river water level (for floods), or a minimum wind speed (for tropical storms or cyclones), or a temperature level (for heat or cold waves). While a good forecast can advise you how much rain will fall and when, however for anticipatory action it’s important to know how much rain is likely to cause a flood and what level of flooding has caused a disastrous impact in the past. The strength or magnitude – also called the threshold – should be set at a level that has required humanitarian assistance in the past.`
  - [x] `Threshold for early action:` field should appear below `Forecast or source of expert judgement` field
  - [x] `Threshold for early action:` field should be a long text field
 
- [x] `Lead time for early action:`
  - [x] `Lead time for early action:` field should have the guidance text: `The lead time is the amount time between when a forecast of an imminent event is issued/received and the impact (or the peak of the impact) of the hazard. National Societies need to implement the readiness and early action activities in the lead time if they are going mitigate or reduce the impact of a hazard.`
  - [x] `Lead time for early action:` field should appear below `Threshold for early action`
  - [x] `Lead time for early action:` field should be a long text field

### Action/Needs

- [x] `Does the National Society have the mandate to act before the impact of the hazard?` 
  - [x] `Does the National Society have the mandate to act before the impact of the hazard?` field should have the guidance text: `Why is the NS in a good position to anticipate the needs of at-risk population to avoid or reduce the negative impact of the disaster?`
  - [x] `Does the National Society have the mandate to act before the impact of the hazard?` field should appear on the top of `Actions/Needs` section.
  - [x]  `Does the National Society have the mandate to act before the impact of the hazard?` field should be a long text field.
- [x] `Does the National Society have EAPs or simplified EAPs active, triggered or under development?`
  - [x] `Does the National Society have EAPs or simplified EAPs active, triggered or under development?` field should have the guidance text: ` Mention the hazards and status of the protocols`
  - [x] `Does the National Society have EAPs or simplified EAPs active, triggered or under development?` field should appear below `Does the National Society have the mandate to act before the impact of the hazard?`.
  - [x]  `Does the National Society have EAPs or simplified EAPs active, triggered or under development?` field should be a long text field.

- [x] ` Has the National Society implemented relevant Disaster Risk Reduction activities in the same geographical area that this plan builds upon?`
  - [x] `Has the National Society implemented relevant Disaster Risk Reduction activities in the same geographical area that this plan builds upon?` field should appear below `Is the National Society implementing other mitigating measures through other sources of funds?`  
  - [x]  `Has the National Society implemented relevant Disaster Risk Reduction activities in the same geographical area that this plan builds upon?` field should be a long text field.
 
- [x] ` Has any other actor in the country activated an early action protocol?`
  - [x] `Has any other actor in the country activated an early action protocol?` should have guidance text `add link(s) to relevant documentation/publication`
  - [x] `Has any other actor in the country activated an early action protocol?`  should appear below UN or other actors.
  - [x] `Has any other actor in the country activated an early action protocol?` should be long text field.
  - [x] `Has any other actor in the country activated an early action protocol?` should have option to upload files.

- [x] After selecting needs by sector in `Anticipated needs` two new sub fields are added instead of one, under needs title (Update)
  - [x] New Sub fields: `Current needs of population at risk` and `Expected needs for immediate assistance if the population is impacted.`

### Operation
- [x] `Who will be targeted through this operation?` (Update)
  - [x] Instead of one text field will have two long text fields
  - [x] New sub fields : `Targeting of population at risk for the early actions` and `Targeting of the expected impacted population if the disaster materializes for the immediate response activities.`

- [x] `Explain the selection criteria for the targeted population ` (Update)
  - [x] Instead of one text field will have two long text fields
  - [x] New sub fields : `For population at risk for the early actions` and `For the expected impacted population if the hazard materializes for the immediate response activities` 

- [x] ` Total Targeted Population` (Update)
  - [x] Fields will be duplicated and end up with two subtitles:
    - [x] ` Early action activities` and `Immediate response activities`

- [x] `People targeted by early actions`
  - [x] `People targeted by early actions` should appear below `Budget`.
  - [x] `People targeted by early actions` should be number field.

- [x]  `People targeted by immediate response`
  - [x] `People targeted by immediate response` should appear below `People targeted by early actions`
  - [x] `People targeted by immediate response` should be number field

- [ ] `List of activities` (Update)
  #771 

### Operational timeframe and contacts 
 
- [x] `IFRC focal point for the anticipatory action`
  - [x] ` IFRC focal point for the anticipatory action:` field should be below `IFRC focal point for the emergency:`
  - [x] `IFRC focal point for the anticipatory action:` should have `Name`, `Title`, `Email`, `Phone Number`.

### Backend:
  - [x] Define the schema/database structure to accommodate the new field.
  - [x] Ensure the database table/column for storing the field is created or updated accordingly.
  - [x]  Implement API endpoints
  - [x] Verify that the new field is appropriately included in request payloads for create and update operations.
  - [x] Test error scenarios to ensure that appropriate error codes and messages are returned to the client.
 
  ### Frontend:
  - [x] The new field must be displayed prominently on the specified page/screen.
  - [x] Input validation should be implemented to ensure data integrity and user error prevention.
  - [x] Validate error messages and ensure they provide clear guidance to users in case of incorrect input.
  - [x] Implement error handling mechanisms to provide meaningful error messages in case of invalid input or other failures.
