### ISSUE TITLE
DREF Application: Label and description updates

### ISSUE THREAD

**Issue by shreeyash07** [IFRCGo/go-web-app#704]
## Task Description
Change the label and description of fields in DREF Application when the type of DREF is `Imminent` 

## Expected Behavior
- [x] Event Details >  `Provide any updates in the situation since the field report and explain what is expected to happen.` should be rename to `What is expected to happen and when?`
  - [x] `What is expected to happen and when?` should have guidance text `Provide sufficient information to prove that the foreseen hazard is expected to have significant humanitarian impact, beyond seasonal scale. If possible, compare this expected event with previous ones that have caused humanitarian impact. Include clear data showing the probability of the event happening, the expected date of impact and the anticipated magnitude. Refer to imminent DREF guidelines for more information on eligible triggers.`
- [x] Event Details >  `Explain why your National Society is acting now and what criteria is used to launch this operation.` Should be renamed to `Why is your National Society acting now and what criteria (forecast or expert judgement) is used to launch this operation?`
  - [x] Guidance text should be change to ` Explain the rationale of this request: how will the proposed plan intends to mitigate the impact of the foreseen hazard? How does the proposed plan complement other humanitarian efforts if any`.
- [x] Event Details >  `Upload any supporting documentation if relevant (Optional)` should be renamed to `Forecast and source of expert judgement`
- [x] Event Details >  `Source of Information` is moved to `Forecast and source of expert judgement`. 
- [x] Actions/Needs > Remove Guidance text from `Current National Society Actions` field
- [x] Actions/Needs > `Government has requested international assistance` is moved below `Are there major coordination mechanisms in place?`
- [x] Operation > Add guidance text to `Overall objective of the operation` field. Guidance Text `Explain what types of expected impacts are prioritized for the mitigation activities and what type of immediate needs will be addressed by the immediate response activities. If the National Society has a contingency plan for this hazard, the operational objective should be aligned with its objectives.`
- [x] Operation > `Operation strategy rationale` renamed to `Mitigation and Immediate Response Strategy Rationale`
  - [x] Add Guidance text `The National Society should explain how the proposed early actions are expected to mitigate or prevent the impact of the disaster on the most at-risk population and to what extent the immediate response activities will address the most pressing needs and constitute a gap not covered by other humanitarian actors.`
- [x] Operation > Add Guidance text to `Planned Intervention` field Guidance Text: ` Three types of activities are eligible under this DREF modality:
Readiness activities: activities which are essential for the National Society to have the capacity to implement the early actions. 
Early actions: activities which will prevent or mitigate the expected impact of the hazard on the most vulnerable population, not yet impacted by the disaster, but at risk of being exposed and highly impacted.
Immediate response: activities to be implemented only if the disaster occurred and within the first two weeks from the date of occurrence of the disaster. This block aims at reducing the gap of activities and funding in the first hours and days after the disaster happens. 
The focus of this operation should be the early action activities, which aim to save lives and protect homes and livelihoods for at risk communities in advance of a hazard. The time to implement the readiness + the early actions should be equal or below the lead time. The time to implement the immediate response should be equal or less than 15 days.`
- [x] Operation > Add Guidance text to `How many staff and volunteers will be involved in this operation. Briefly describe their role.` Guidance text: `
Provide sufficient information to demonstrate that the National Society has the capacity to implement the readiness and early actions within the lead time.`
- [ ] Operation > `Persons Targeted` renamed to `Total people targeted` with the logic of sum of two new fields: `People targeted by early actions` and  `People targeted by immediate response`

## Acceptance Criteria
- [ ] All the necessary changes should reflect on the Application filed when DREF Type is `Imminent`

**Comment by shraeyaa** [comment]
- [x] Actions/Needs 
     - [ x] Reduce the gap below Current National Society Actions
     - [x] Actions/Needs - 'Are there major coordination mechanisms in place?' should display a description section right below it after clicking on 'Yes'
     - [ ] Change the name 'Anticipated Needs' to 'Needs by sector'
- [ ] Operation - The guidance text of Planned Intervention is not complete
- [ ] Event Detail:
     - [ ] 'Date of the Event / Date when trigger was met' field should be hidden
     - [ ] 'Forecast or source of expert judgement should contain a button to 'Upload document' and 'Add new source information'
     - [ ] 'Scope and scale of the event' field is replicated
     - [ ] 'Forecast and source of expert judgement' field is replicated 
     - [ ]  'Upload photos (e.g. impact of the events, NS in the field, assessments)' should be hidden

cc @shreeyash07
