### ISSUE TITLE
DREF Operation Update > DREF Imminent Application to DREF Response Ops Update: Additions

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#705]
## Task description
List of new fields that are required to be added in the DREF Operational Update when DREF `Imminent` Application changes to DREF Response in Ops Update.

## Expected Behaviors
When the type of DREF is `Response` in the ops Update, the following fields should be added to the DREF Operation Update:

- **Operation Overview** 
   - [x] New field `Additional allocation requested` which should appear in the Operation Overview tab below the `Budget Allocated so far`.
   - [x]  New field `Total DREF` which should appear in the Operation Overview tab above the `Emergency appeal planned`.
- **Event Details**
- [ ] New field `Summary of change` which should appear in the Event Details tab above the  `Date of disaster`.

- [ ] `Threshold for early action:`
  - [ ] `Threshold for early action:` field should have the guidance text: `A threshold is a value or a combination of values from which it is considered that the hazard will cause major humanitarian impact, such as an amount of rainfall combined with a river water level (for floods), or a minimum wind speed (for tropical storms or cyclones), or a temperature level (for heat or cold waves). While a good forecast can advise you how much rain will fall and when, however for anticipatory action it’s important to know how much rain is likely to cause a flood and what level of flooding has caused a disastrous impact in the past. The strength or magnitude – also called the threshold – should be set at a level that has required humanitarian assistance in the past.`
  - [ ] `Threshold for early action:` field should appear below `Why is your National Society acting now and what criteria (forecast or expert judgement) is used to launch this operation?` field
  - [ ] `Threshold for early action:` field should be a long text field
 
- [ ] `Lead time for early action:`
  - [ ] `Lead time for early action:` field should have the guidance text: `The lead time is the amount time between when a forecast of an imminent event is issued/received and the impact (or the peak of the impact) of the hazard. National Societies need to implement the readiness and early action activities in the lead time if they are going mitigate or reduce the impact of a hazard.`
  - [ ] `Lead time for early action:` field should appear below `Threshold for early action`
  - [ ] `Lead time for early action:` field should be a long text field

- **Actions/Needs**
- [x] Add a new field `Add any photos of National Society operation`  which should appear in the Event Details tab below the `When did the National Society start responding` field.
- [ ] `Does the National Society have the mandate to act before the impact of the hazard?` 
  - [ ] `Does the National Society have the mandate to act before the impact of the hazard?` field should have the guidance text: `Why is the NS in a good position to anticipate the needs of at-risk population to avoid or reduce the negative impact of the disaster?`
  - [ ] `Does the National Society have the mandate to act before the impact of the hazard?` field should appear below 'When did the National Society start responding?' field
  - [ ]  `Does the National Society have the mandate to act before the impact of the hazard?` field should be a long text field.
- [ ] `Does the National Society have EAPs or simplified EAPs active, triggered or under development?`
  - [ ] `Does the National Society have EAPs or simplified EAPs active, triggered or under development?` field should have the guidance text: ` Mention the hazards and status of the protocols`
  - [ ] `Does the National Society have EAPs or simplified EAPs active, triggered or under development?` field should appear below `Does the National Society have the mandate to act before the impact of the hazard?`.
  - [ ]  `Does the National Society have EAPs or simplified EAPs active, triggered or under development?` field should be a long text field.
- [ ] `Is the National Society implementing other mitigating measures through other sources of funds?` field should appear below `Does the National Society have EAPs or simplified EAPs active, triggered or under development?`  
- [ ] ` Has the National Society implemented relevant Disaster Risk Reduction activities in the same geographical area that this plan builds upon?`
  - [ ] `Has the National Society implemented relevant Disaster Risk Reduction activities in the same geographical area that this plan builds upon?` field should appear below `Is the National Society implementing other mitigating measures through other sources of funds?`  
  - [ ]  `Has the National Society implemented relevant Disaster Risk Reduction activities in the same geographical area that this plan builds upon?` field should be a long text field.
- [x] ` Has any other actor in the country activated an early action protocol?`
  - [ ] `Has any other actor in the country activated an early action protocol?` should have guidance text `add link(s) to relevant documentation/publication`
  - [ ] `Has any other actor in the country activated an early action protocol?`  should appear below UN or other actors.
  - [ ] `Has any other actor in the country activated an early action protocol?` should be long text field.
  - [ ] `Has any other actor in the country activated an early action protocol?` should have option to upload files.
- **Operation**
   - [x] Add a new field `People targeted by response` which should appear in the Operation tab above the `Persons targeted` field
- **Operational timeframe and contacts** 
   - [x] Add a new field `Reporting timeframes start` which should appear in the Operational timeframe and contacts tab below the Operational Timeframes tab.
   - [x] Add a new field `Reporting timeframe end date` which should appear in the Operational timeframe and contacts tab above the Tracking Data and contacts. 
  
### Backend:
  - [x] Define the schema/database structure to accommodate the new field.
  - [x] Ensure the database table/column for storing the field is created or updated accordingly.
  - [x]  Implement API endpoints
  - [ ] Verify that the new field is appropriately included in request payloads for create and update operations.
  - [ ] Test error scenarios to ensure that appropriate error codes and messages are returned to the client.
 
  ### Frontend:
  - [x] The new field must be displayed prominently on the specified page/screen.
  - [x] Input validation should be implemented to ensure data integrity and user error prevention.
  - [x] Validate error messages and ensure they provide clear guidance to users in case of incorrect input.
  - [x] Implement error handling mechanisms to provide meaningful error messages in case of invalid input or other failures.
