### ISSUE TITLE
DREF Operation Update > DREF Imminent Application to DREF Response Ops Update: Label and description updates

### ISSUE THREAD

**Issue by barshathakuri** [IFRCGo/go-web-app#708]
## Task description
Change the label and description of fields in in the DREF Operational Update when DREF `Imminent` Application changes to DREF Response in Ops Update.

## Expected Behaviors
When the type of DREF is `Response` in the ops Update, the following fields label and description should be changed to the DREF Operation Update:

- **Operation Overview**
   - [x] `Hazard details` field should change to `Disaster Details` in DREF Operation Update.
   - [x] `At Risk Country and Region(s)`  field should change to `Affected Region(s)`.
   - [x] `Request Amount in CHF` field should change to `Budget Allocated so far`
   - [x] Add new field `Additional` allocation requested.
- **Event Details**  
   - [x] `Estimated people in need (Optional)` field should change to `Estimated population affected`
   - [x]  `Provide any updates in the situation since the field report and explain what is expected to happen` should change to `What happened, where and when?` with description `Please update this section with information regarding the impact of the disaster: explain when the event materialized, whether it occurred as predicted in terms of magnitude and geographical area, or whether these expectations have been exceeded.`
   - [ ] Event Details >  `Explain why your National Society is acting now and what criteria is used to launch this operation.` Should be renamed to `Why is your National Society acting now and what criteria (forecast or expert judgement) is used to launch this operation?`
   - [ ] Guidance text should be change to ` Explain the rationale of this request: how will the proposed plan intends to mitigate the impact of the foreseen hazard? How does the proposed plan complement other humanitarian efforts if any`.
   - [x] `Scope and scale` field should change to `Scope and Scale of the event` with description `Describe the extent this disaster has impacted negatively on lives, livelihoods and infrastructure. Explain who has been impacted by the disaster? Where do they live, and why are they vulnerable? Please explain which groups (e.g elderly, children, people with disabilities, IDPs, Refugees, etc.) have been most impacted. `
- **Actions/Needs**
   - [x] `Did the National Society start any anticipatory actions?` should change to ` When did the National Society start responding?`  
   - [x] `Anticipated Needs` should change to `Needs (gaps) identified`.

## Acceptance Criteria
- [x] All the necessary changes should reflect on the operational update.
