### ISSUE TITLE
DREF Application: Visibility updates

### ISSUE THREAD

**Issue by shreeyash07** [IFRCGo/go-web-app#709]
## Task Description
Changes the visibility of the fields when the type of DREF is `Imminent`.

## Expected Behaviors
- [ ] Hide the following fields
  - Operation Overview
    - [x] `Disaster Category`
    - [x] `If available, please update Crisis categorization analysis.`
    - [x] `Emergency appeal planned.`
  - Event Details
    - [x] `Approximate date of impact`
    - [x] `Estimated people in need (Optional)`
    - [ ] `Upload photos (e.g. impact of the events, NS in the field, assessments)`
  - Action/Needs
    - [x] `Did the National Society start any anticipatory actions?`
    - [x] `Select the actions that apply.`
    - [x] `Any identified gaps/limitations in the assessment`
  
## Acceptance Criteria
- [ ] All above mentioned fields should be hidden when the type of DREF is `Imminent`

**Comment by shraeyaa** [comment]
- [ ] Event Detail - 'Upload photos (e.g. impact of the events, NS in the field, assessments)' should be hidden

cc @shreeyash07
