### ISSUE TITLE
DREF Application: Add sub-fields in `List of activities`

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#771]
## Task Description
Currently, there is a `List of Activities` section. Now the `List of Activities` section will be replaced by 3 new blocks. 3 new sections being: 
- Readiness
- Early Actions
- Early Response 
Under each of these 3 new sections, there will be 2 fields: Title and Timeframe

### Frontend
- [ ] `List of Activities` section should be replaced by `Readiness`, `Early Actions`, and `Early Response` blocks
- [ ] Under each of the 3 new blocks, there should be an `Add Activities` button to add activities 
- [ ] When the user clicks on the `Add Activities` button, 2 fields and a delete button should appear. 2 fields being: `Title` and `Timeframe`. An example screenshot is attached below
<img width="885" alt="Screenshot 2024-03-14 at 11 00 21" src="https://github.com/IFRCGo/go-web-app/assets/72339626/85df6a99-a14f-4d54-a6bc-3b4ce68a52fa">

### Backend 

- [x] Each new block should have multiple activities and timeframes
- [ ] The old `List of Activities` data should be mapped to the `Early Actions` block
- [ ] The old `List of Activities` data should not have any timeframe
- [ ] The activities should not have bullets in the form, but the bullet should appear in the export

### Reference screenshot
![IMG_1223](https://github.com/IFRCGo/go-web-app/assets/72339626/83ab2e9f-0d29-452d-bc67-fe176a36732c)

### Backend:
  - [x] Define the schema/database structure to accommodate the new field.
  - [x] Ensure the database table/column for storing the field is created or updated accordingly.
  - [x]  Implement API endpoints
  - [x] Verify that the new field is appropriately included in request payloads for create and update operations.
  - [ ] Test error scenarios to ensure that appropriate error codes and messages are returned to the client.
 
  ### Frontend:
  - [ ] The new field must be displayed prominently on the specified page/screen.
  - [ ] Input validation should be implemented to ensure data integrity and user error prevention.
  - [ ] Validate error messages and ensure they provide clear guidance to users in case of incorrect input.
  - [ ] Implement error handling mechanisms to provide meaningful error messages in case of invalid input or other failures.
