### ISSUE TITLE
DREF - New Import functionality (Excel)

### ISSUE THREAD

**Issue by anamariaescobar** [IFRCGo/go-web-app#811]
As discussed this morning in our call, we are bringing back the import functionality for the DREF Application, this time in Excel.
Actions points from this meeting:

**DFS**
- [x] #812
- [x] #813
- [x] Start estimating amount of hours to complete this request
- [ ] Estimate amount of hours spent on the Imminent changes
- [x] #1288 
- [x] #1306
- [x] #1431

**IFRC**
- [x] Complete the draft template started by DFS and work on the rest of the templates following the same structure
- [ ] Provide an analysis on who is starting DREFs

@tovari @marcovvu1 @udaynwa @samshara @frozenhelium

**Comment by anamariaescobar** [comment]
Adding in here the word template to try to mimic the new Excel template.

[DREF.Request.Import_Sudden.Slow_v220906 (1).docx](https://github.com/IFRCGo/go-web-app/files/15249222/DREF.Request.Import_Sudden.Slow_v220906.1.docx)

@tovari @marcovvu1 @udaynwa @samshara @frozenhelium
