### ISSUE TITLE
Update the map view for healthcare data

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#823]
## Task description
- We need to update the map view of NS Local Units for the healthcare data 

### To do
- [x] Add pointers in the map for healthcare data
- [x] Add pop-up (with details similar to `Admin` local units type) when clicking on the pointers in the map
- [x] Add map legends with `Healthcare`
- [x] When filtered down to a specific `Local Unit type`, the map should reflect the sub-type of the particular local unit. The legends should be updated accordingly.

### Links
- Figma wireframes: https://www.figma.com/proto/H9mZfGeXtlzK6HPzttYoci/IFRC-GO---Wires-Current---1?page-id=2%3A68604&type=design&node-id=3856-49130&viewport=2538%2C-1789%2C0.28&t=bOW8frnGS6h41erL-1&scaling=scale-down-width&starting-point-node-id=3856%3A49130&hide-ui=1
- Staging link of NS Local Units: https://go-stage.ifrc.org/countries/3/ns-overview/context-and-structure
