### ISSUE TITLE
Add tabular view for NS Local Units

### ISSUE THREAD

**Issue by udaynwa** [IFRCGo/go-web-app#824]
## Task description
1. We need to add `List view` for NS Local Units

### To-do
- [x] Add the `List view` toggle next to the `Map view`
- [x] List view should have following columns:
  - [x] Name (EN)
  - [x] Address (EN)
  - [x] Type 
  - [x] Focal person (EN)
  - [x] Phone number
  - [x] Email 
  - [x] Validated 
  - [x] Actions
2. On the Actions column there should be `Edit` and `Delete` options for `Local Unit Admin`.
### Links
- Figma wireframes: https://www.figma.com/proto/H9mZfGeXtlzK6HPzttYoci/IFRC-GO---Wires-Current---1?page-id=2%3A68604&type=design&node-id=3856-50523&viewport=2538%2C-1789%2C0.28&t=bOW8frnGS6h41erL-1&scaling=scale-down-width&starting-point-node-id=3856%3A49130&hide-ui=1
- Staging link of NS Local Units: https://go-stage.ifrc.org/countries/3/ns-overview/context-and-structure

### Update (2024-05-27)

- [x] #1109

CC: @tovari

**Comment by frozenhelium** [comment]
We should remove details regarding the focal person according to the discussion with @tovari 
  - Name
  - Phone Number
  - Email
