### ISSUE TITLE
Preparedness (PER) - April 2024 refinements

### ISSUE THREAD

**Issue by tovari** [IFRCGo/go-web-app#888]
A few things to improve on PER:

PER export:

~~- [ ] #982
[PER NS - Level Performance - Example Report.pdf](https://github.com/IFRCGo/go-web-app/files/15112252/PER.NS.-.Level.Performance.-.Example.Report.pdf)~~
- [x] #983

Component Rating Results:

- [x] #984

Translations:

- [x] #936

Considerations for each component:

- [x] #1352

**Comment by tovari** [comment]
@szabozoltan69, would you mind to update the spanish, french and arabic translations of

- [x] component titles
- [x] component descriptions
- [x] form question groups
- [x] questions
- [x] form areas
- [x] form answers

[per_translations_(restructured)-to_import.xlsx](https://github.com/IFRCGo/go-web-app/files/15250888/per_translations_.restructured.-to_import.xlsx)

Thanks!

**Comment by szabozoltan69** [comment]
I'll update them in these tables:

- [x] component titles - formcomponent/title
- [x] component descriptions - formcomponent/description
- [x] form question groups - formquestiongroup/title
- [x] questions - formquestion/description
- [x] form areas - formarea/title
- [x] form answers - formanswer/title.

**Comment by szabozoltan69** [comment]
[6.zip](https://github.com/IFRCGo/go-web-app/files/15266852/6.zip)
SQL update scripts were running fine on Staging.

**Comment by tovari** [comment]
Need to ask a few updates:

- [x] "Epi considerations" change to "Epidemic considerations"
- [x] "Type of Operation" change to "PER Areas" ![Image](https://github.com/user-attachments/assets/05493f0f-8dc4-49cd-abd1-33848234280d)
- [x] PDF export: Change country name in the title to the NS name
- [x] PDF export: Top right corner: replace "PER" with the PER logo ![Image](https://github.com/user-attachments/assets/b233a5c1-d0a7-4921-a61b-095ff691c454)
